---
title: "Mudanças das vazões afluentes aos reservatórios do Ceará"
description: |
  Estudos e soluções tecnológicas visando o aumento da resiliência às secas
author:
  - name: "Jorgiane Pires Bezerra"
    url: 
    affiliation: Aluna de mestrado da Universidade Federal do Ceará (UFC) 
    affiliation_url: https://www.funceme.br
    orcid_id: 
  - name: "Francisco Chagas Vasconcelos Junior"
    url: 
    affiliation: Fundação Cearense de Meteorologia e Recursos Hídrios (FUNCEME) 
    affiliation_url: https://www.funceme.br
    orcid_id: 0000-0002-1558-8383
  - name: "Dirceu S. Reis Jr."
    url: https://github.com/DirceuReis
    affiliation: Professor Universidade de Brasília (UnB) 
    affiliation_url: https://www.unb.br
    orcid_id: 0000-0003-1787-9763
  - name: "Eduardo Sávio P. R. Martins"
    url: 
    affiliation: Presidente da FUNCEME 
    affiliation_url: https://www.funceme.br
    orcid_id: 0000-0003-1787-9763
    
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

## Apresentação

Este estudo de avaliação das mudanças nas vazões afluentes aos reservatórios do Estado do Ceará está inserido num projeto de pesquisa maior, desenvolvido pela Fundação Cearense de Meteorologia e Recursos Hídricos (Funceme) do Estado do Ceará, intitulado **Estudos e soluções tecnológicas visando o aumento da resiliência às secas**. O objetivo geral desse projeto de pesquisa é subsidiar as decisões e orientar a elaboração de políticas públicas do setor de recursos hídricos da bacia hidrográfica do Rio Banabuiú. 

O projeto **Estudos e soluções tecnológicas visando o aumento da resiliência às secas** tem como foco as seguintes atividades:

1- avaliar o aumento da demanda hídrica devido à expansão das áreas irrigadas;

2- entender como as mudanças do uso do solo, o que inclui a construção de pequenos reservatórios espalhados na bacia, podem afetar as mudanças na oferta hídrica da bacia;

3- estimar os impactos das mudanças do clima nas vazões afluentes aos reservatórios.    

Este estudo de **avaliação das mudanças das vazões afluentes aos reservatórios do Ceará** foca no item (3) da lista acima. Compreender e quantificar o regime de vazões afluentes aos diferentes reservatórios da região do estudo para diferentes cenários no futuro é um elemento-chave para o panejamento e a gestão dos recursos hídricos. 

AS séries temporais de vazão afluente aos reservatórios nos mais diferentes cenários de planejamento permite que se simule a operação dos macro-sistemas e se avalie diferentes políticas operativas.


## Motivação

Este estudo tem como principal motivação a construção de uma metodologia e a estimativa das mudanças no regime de vazão oriunda única e exclusivamente das mudanças do clima, mais especificamente de mudanças no padrão das preciptações e da temperatura, o que afeta a magnitude da evapotranspiração potencial na região. 

Estimar os impactos no regime de vazões afluentes aos reservatórios monitorados pela COGERH, para diferentes cenários e diferentes períodos futuros, permitirá, na sequência, a execução de um estudo complementar, em que será possível identificar as principais repercussões para a gestão dos recursos hídricos, assim como para avaliar diferentes estratégias adpatativas. 


## Atividades


## Cronograma

